name: Build and release
on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux-x86_64
          - os: macos-13
            platform: macos-x86_64
          - os: macos-14
            platform: macos-arm64
    steps:
      - uses: actions/checkout@v4

      - name: Install Linux build dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev libwayland-dev libxkbcommon-dev

      - name: Generate headers
        run: python tools/build_assets.py && python tools/generate_tables.py

      - name: Build and package
        run: chmod +x ./tools/build_release.sh && ./tools/build_release.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.platform}}-build
          path: gce-*.tar.gz

      - name: Upload to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: gce-*.tar.gz

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            git
            zip
            python
            base-devel
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-ninja

      - uses: actions/checkout@v4

      - name: Set up environment path for UCRT64
        run: |
          export PATH="/ucrt64/bin:$PATH"
          which cmake
          cmake --version

      - name: Generate headers
        run: |
          export PATH="/ucrt64/bin:$PATH"
          python tools/build_assets.py && python tools/generate_tables.py

      - name: Configure
        run: |
          export PATH="/ucrt64/bin:$PATH"
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DENABLE_PACKAGING=ON

      - name: Build
        run: |
          export PATH="/ucrt64/bin:$PATH"
          cmake --build build

      - name: Install
        run: |
          export PATH="/ucrt64/bin:$PATH"
          cmake --install build --prefix dist


      - name: Archive binary
        run: |
          export PATH="/ucrt64/bin:$PATH"
          mv dist/bin gce-windows-x64
          cp /ucrt64/bin/libstdc++-6.dll gce-windows-x64/
          cp /ucrt64/bin/libgcc_s_seh-1.dll gce-windows-x64/
          cp /ucrt64/bin/libwinpthread-1.dll gce-windows-x64/

          zip -r gce-windows-x64.zip gce-windows-x64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: gce-*.zip

      - name: Upload to GitHub Release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: gce-windows-x64.zip
